# refs: https://docs.docker.com/compose/compose-file/
#       https://hub.docker.com/_/postgres/

version: "3"

services:
  nueip-db:
    image: pgdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: nueip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
